# Generated by Django 4.0.3 on 2022-04-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.UUIDField(default='374db7c925fd4406971f7a4da85c5244', primary_key=True, serialize=False),
        ),
    ]
